MEDIARITHMICS/plugins-nodejs-sdk

src/core/class/mediarithmics/common/BasePlugin.ts

The arguments 'isJson' & isBinary are optional in requestGatewayHelper. When not given, they should have a default value.
Example with 'isJson': The previous implementation was setting the request option 'json' field to true by default before checking
wether isJson was defined (and if it was defined, what was its state).
The previous implementation tried to override the request option json field with Object.assign(). But, this is not what Object.assign()
is doing (or should be used for) => in case of overriding an already existing property, it is using the value of the last argument having it.
In our case, it was the initial 'options' variable which was provided last, hence we were keeping the default value of json => it was impossible to override
the json request property.
The same was …

Fix overriding request options parameters in requestGatewayHelper

---

src/core/class/mediarithmics/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
src/core/interfaces/mediarithmics/api/audience-feed-connector/AudienceFeedConnectorPluginResponseInterface.ts

When being called on the external_segment_connection endpoint, the plugins should now:
- Return 200 if everything was OK
- Return 502 if the external API is not OK yet (ex: segment is not fully ready on the 3rd party side)
- Return 500 if something else was wrong

Update API of ExternalSegmentCreation

---

package-lock.json
package.json
src/core/class/mediarithmics/ad-renderer/AdRendererBasePlugin.ts

We're putting some values passed by the plugin impl in an
HTTP Header in the AdRenderer plugin SDK.
The HTTP spec is asking to only put Latin1 characters. Node
throw an error when an invalid character is detected.
Using ACSII safe codes in our JSON should prevent any potential issues.

Fix invalid characters issues in the DisplayContext header

---

README.md
examples/activity-analyzer/src/MyPluginImpl.ts
src/mediarithmics/api/datamart/UserActivityInterface.ts

Since 0.4.0, it was impossible to:
- Use a custom event name
- Extend `core.UserActivityEvent` as a class (as it's now a type)
Hence, this commit is:
- Adding `string` as a possible EventName to let users use custom event
name
- Adding a new migration line in REAME.md to invite users to use
`core.GenericUserActivityEvent` instead of `core.UserActivityEvent` if
they are extending it.
- Adding those types operation in the Dummy Activity analyzer so that we
can check for any regression while developping new versions of the SDK.

Fix Activity Analyzer types issues

---

CHANGELOG.md
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
src/mediarithmics/plugins/recommender/RecommenderBasePlugin.ts

- Rename the `recommenderProperties` field to `properties` for
Recommender support
- Change the type of `properties` in the Instance Context of Audience
Feed & Recommender from `PluginProperty[]` to `PropertiesWrapper`

Refactor some Instance Context

---

src/mediarithmics/api/datamart/UserActivityInterface.ts
src/mediarithmics/api/reference/UserIdentifierInterface.ts

The compartment_id in the activities or events should be a `string` instead of a number.
I've updated the interface of api/datamart repository to reflect that.
Note that it should also be a string within the UserIdentifierInterface but as of today the back is using it as a `number`.
I've set a reminder in the code so that when the back is updated we'll also update the interface in the plugin sdk

Update compartment_id type

---

README.md
package-lock.json
package.json
src/mediarithmics/api/datamart/UserActivityInterface.ts

We were misisng some `$`...
Hopefully, once the type are auto-generated, we won't have those issues
anymore.

[MICS-127] Fix interface UserActivity.EmailHash

---

CHANGELOG.md
package-lock.json
package.json
src/mediarithmics/plugins/activity-analyzer/ActivityAnalyzerBasePlugin.ts
src/mediarithmics/plugins/ad-renderer/base/AdRendererBasePlugin.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
src/mediarithmics/plugins/bid-optimizer/BidOptimizerBasePlugin.ts
src/mediarithmics/plugins/common/BasePlugin.ts
src/mediarithmics/plugins/email-renderer/base/EmailRendererBasePlugin.ts
src/mediarithmics/plugins/email-router/EmailRouterBasePlugin.ts
src/mediarithmics/plugins/recommender/RecommenderBasePlugin.ts
src/tests/BasePluginTests.ts

In order to avoid having 'bursts' effects on the Gateway APIs calls that
are being done when the instance context is re-built, we're now adding
some variability in the refresh period (+10%).
We also updated the refresh period from 2min to 10min.
This should lower the Gateway API load and provide a better plugin
stability / performance.

Add variability in the instance context refresh interval

---

package-lock.json
package.json

`lodash` and `marked (via `typedoc`) had security issues. Updating the libs solve the issue.
For reference:
- https://www.npmjs.com/advisories/1065
- https://www.npmjs.com/advisories/812
- https://www.npmjs.com/advisories/1076

Upgrade lodash/typedoc to fix security warnings

---

CHANGELOG.md
src/mediarithmics/plugins/common/BasePlugin.ts

- Updating log level:  `/v1/log_level` method was broken since upgrade to wiston 3.x.
- Log_level was set up at the level of the transport object and then frozen. Now, it's by default set up at the level of the logger object, which allows us to modify it at runtime.

BasePlugin | Fix Logger

---

src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts

The Yoda team is working on enabling the file drop from the audience external feeds plugins.
It requires an update of the onUserSegmentUpdate to pass two new arguments that are 
- the line to be built
- the file content type
This PR aims at updating the interface of the method and provide a test to cover this.

MICS-DEV - Update Interfaces of onUserSegmentUpdate

---

CHANGELOG.md
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
src/tests/AudienceFeedConnector.ts

when calling onUserSegmentUpdate init method, the code was building the plugin response manually.
New parameters have been added (data & stats) that were not computed.
I've updated the tests to reflect that also

Fix data & stats not passed to the plugin response

---

src/mediarithmics/plugins/activity-analyzer/ActivityAnalyzerBasePlugin.ts
src/mediarithmics/plugins/ad-renderer/base/AdRendererBasePlugin.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
src/mediarithmics/plugins/bid-optimizer/BidOptimizerBasePlugin.ts
src/mediarithmics/plugins/common/BasePlugin.ts
src/mediarithmics/plugins/email-renderer/base/EmailRendererBasePlugin.ts
src/mediarithmics/plugins/email-router/EmailRouterBasePlugin.ts
src/mediarithmics/plugins/recommender/RecommenderBasePlugin.ts
src/tests/ActivityAnalyzerTests.ts

With the lifecycle of the plugin, we should not get any request before
getting a `/v1/init` call and changing the health check response.
However, in some edge cases, we can get a race condition where a small
number of requests can still be sent. We don't have any credentials so
we can't prepare the context and can't properly handle the request.
However, if we don't stop ASAP the request we will save in the cache a
failed promise which will fail *all* requests for 10 minutes (for a
given instance id). Now, we still loose the extra early call(s) but
start processing correctly as soon as the initialization kicks in.

FIX: Refuse to process calls before the initialization

---

CHANGELOG.md
examples/custom-action/src/tests/index.ts
src/mediarithmics/plugins/custom-action/CustomActionBasePlugin.ts
src/mediarithmics/plugins/custom-action/CustomActionInterface.ts
src/tests/CustomActionBaseTest.ts

instance_id is replaced by custom_action_id in CustomActionRequest,
in order to have a more meaningful name.

MICS-7419 Change CustomActionRequest

---

examples/activity-analyzer/src/tests/index.ts
examples/bid-optimizer/src/tests/index.ts
examples/custom-action/src/tests/index.ts
examples/email-renderer/src/tests/index.ts
examples/email_router/src/tests/index.ts
examples/handlebars-ad-renderer/src/tests/index.ts
examples/simple-ad-renderer/src/tests/index.ts
examples/simple-ad-renderer/test.sh
src/helpers/ActivityAnalyzerTestHelper.ts
src/mediarithmics/plugins/common/BasePlugin.ts
src/mediarithmics/plugins/common/ProductionPluginRunner.ts
src/tests/ActivityAnalyzerTests.ts
src/tests/AdRendererBaseTests.ts
src/tests/AdRendererRecoTests.ts
src/tests/AudienceFeedConnector.ts
src/tests/BasePluginTests.ts
src/tests/CustomActionBaseTest.ts
src/tests/EmailRendererTests.ts
src/tests/EmailRouterTests.ts
src/tests/RecommenderTests.ts
testOnly.sh
test_sdk_and_examples.sh

The platform now gives credentials (worker_id/authentication_token) via
the environment. The `CREDENTIAL_UPDATE_FROM_*` mechanism can also be
removed as all processes will get the same env / the same credentials,
and they don't change anymore (for the lifetime of the container).
While not perfect, overriding the env in the tests code avoid a
dependency to a wrapper script.
This is a breaking change: the api changes, all tests must be fixed.

Migrate to the new way to get credentials

---

.npmignore

The examples/ folder can contain a lot of node_modules/ which are not
automatically excluded. The release 0.9.0 weights 500MB instead of the
usual ~500KB because of that. Examples are not needed to run the lib, we
can ignore them.

Remove examples from the bundled npm archive

---

README.md

The 0.8 -> 0.9 changes were at the wrong place (between 0.6 -> 0.7 and
0.5 -> 0.6), it's now fixed.

Update migration steps order

---

CHANGELOG.md
package-lock.json
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
src/tests/AudienceFeedConnector.ts
src/tests/BasePluginTests.ts

The idea behing this change is to return 429 errors code to deplay
message ingestion and to raise errors when batch are failing. Metrics
implementation to enable monitoring and alerting will be handle on
Engineering side
- Update interfaces
- Update code to be able to return a status name = "retry" which returns
a StatusCode = 429 while trying to push audiences to the external
partner (onUserSegmentUpdate method)
- Add a test to check it works
- Switch to new Buffer implementation

MICS-DEV Enable the plugin to return 429 errorCode 

---

package.json

The test dependencies had to be moved from 'devDependencies' to prod
dependencies because of the exported test helper 'itFactory'.

MICS-12762 Move test helper dependencies

---

src/helpers/StatsClient.ts

The `uds` procotol expects a working socket on
`/var/run/datadog/dsd.socket`.
We don't have it during tests and got:
> Error: Socket not created properly. Check previous errors for details.
> Error: connect -2
Outside production we now default to udp on localhost, which does not
fail.

Fix stat clients in tests

---

src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts

This commit renders sync_result mandatory in
UserSegmentUpdatePluginResponseStats.
It also adds a possible value for SyncResult which is IDENTIFIER_REJECTED.

MICS-14615 SyncResult modification

---

CHANGELOG.md
src/mediarithmics/api/core/batchupdate/BatchUpdateHandler.ts
src/mediarithmics/api/core/batchupdate/BatchUpdateInterface.ts
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
src/tests/BatchedAudienceFeedConnector.ts

To simplify downstream API, this commit adds 2 new abstract classes to isolate plugin with or without batching feature.
Thanks to this, it's easy to see in implementation if plugin implements `AudienceFeedConnectorBasePlugin` or
`BatchedAudienceFeedConnectorBasePlugin<T>`.
When using batch, it also :
- explicits the type of the line, and of the batch context.
- require implementation to provide ser/deserialization methods to string.
- require implementation of the onBatchUpdate.
With the vanilla implementation, the implementation cannot respond with `UserSegmentUpdatePluginBatchDeliveryResponseData`, and cannot override onBatchUpdate.

MICS-15536 Rework AudienceFeedConnectorBasePlugin hierarchy

---

src/helpers/StatsClient.spec.ts
src/helpers/StatsClient.ts

There is a metrics buffer implemented in StatsClient. This commit removes this buffer and uses the one that is already implemented in the lib that we use.

MICS-16538 Repair Datadog metrics

---

src/helpers/StatsClient.spec.ts
src/helpers/StatsClient.ts

This reverts commit 37789e92dd0f42749746e91d0281744f10308404.
This change would break dashboards in a vicious way as the counters are currently resetting to 0 each time. Let's double check with the dashboard team first.

Revert "MICS-16538 Repair Datadog metrics"

---

src/mediarithmics/api/core/audiencesegment/AudienceSegmentInterface.ts
src/mediarithmics/api/core/plugin/PluginPropertyInterface.ts
src/mediarithmics/api/core/plugin/ValueInterface.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts

The selected identifying resources list is no more a plugin property, it's a field of feed instance

MICS-17221 Access selected identifying resources from feed instance

---

CHANGELOG.md
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts

Add new route /v1/troubeshoot.
This will be used primarly to retrieve volumes on third parties.

MICS-18206 Audience Feed add new /troubleshoot route

---

CHANGELOG.md
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts

- `AudienceFeedConnectorBasePlugin` add new optional parameter `forceRefresh?: boolean` to `getInstanceContext`
- `AudienceFeedConnectorBasePlugin` force refresh of instanceContext for `external_segment_creation`

MICS-18286 AudienceFeedConnectorBasePlugin improves cache

---

CHANGELOG.md
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts

`/troubleshoot` was declared as GET instead of POST

MICS-18286 Fix /troubleshoot on feed

---

CHANGELOG.md
src/mediarithmics/plugins/common/BasePlugin.ts

Colors option where adding unescaped characters
which graylog can't handle.

MICS-18136 Fix logger remove colors

---

CHANGELOG.md
README.md
src/mediarithmics/api/core/batchupdate/BatchUpdateHandler.ts
src/mediarithmics/api/core/batchupdate/BatchUpdateInterface.ts
src/tests/BatchedAudienceFeedConnector.ts

Fix typo batching stats, changing:
- send_items_in_success -> sent_items_in_success
- send_items_in_error -> sent_items_in_error

MICS-18670 Typo batching stats

---

CHANGELOG.md
examples/audience-feed/src/ExampleAudienceFeed.ts
examples/audience-feed/src/tests/index.ts
src/mediarithmics/api/core/batchupdate/BatchUpdateHandler.ts
src/mediarithmics/api/core/batchupdate/BatchUpdateInterface.ts
src/tests/BatchedAudienceFeedConnector.ts

Remove fields `sent_items_in_error` and `sent_items_in_success` from `BatchUpdatePluginResponse`. 
Add instead the field `stats` which is an Array of `BatchUpdatePluginResponseStat` containing `errors`, `successes` and `operation` fields. 
It will be used for getting specific error rate for each operation type

MICS-19677 add success/error stats for each operation_type in plugin SDK

---

CHANGELOG.md
src/mediarithmics/api/core/webdomain/UserAgentIdentifierRealmSelectionInterface.ts
src/mediarithmics/index.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
src/tests/AudienceFeedConnector.ts

This commit defines functions to get user agent identifier realm selections for a given datamart, and to check that there exists one realm with a given realm type. These functions can be used in an audience feed connector.

MICS-19771 Realm check in feeds

---

CHANGELOG.md
README.md
examples/audience-feed/src/ExampleAudienceFeed.ts
examples/audience-feed/src/tests/index.ts
src/mediarithmics/api/core/batchupdate/BatchUpdateHandler.ts
src/mediarithmics/api/core/batchupdate/BatchUpdateInterface.ts
src/tests/BatchedAudienceFeedConnector.ts

reintroduce sent_items_in_success and sent_items_in_error instead of stats field in BatchUpdatePluginResponse

MICS-20001 reintroduce sent_items_in_success and sent_items_in_error

---

CHANGELOG.md
examples/computed-field/package.json
examples/computed-field/src/MyComputedField.ts
examples/computed-field/src/tests/MyComputedField.test.ts
package.json
src/mediarithmics/plugins/computed-field/ComputedFieldBasePlugin.ts

We need to provide developers with more details when working
on computing fields, such as the type of data they are receiving
(UserActivity, UserProfile or Computed field result updates) but also
the operation that caused the update (insertion or deletion).
To do so, we need to refactor the structure of the computed field
sdk, enforcing the definition of 3 distincts updates method (one per
data type).
Developer experience should be enhanced this way.

MICS-20510 Update Computed Field plugins structure 

---

CHANGELOG.md
examples/computed-field/src/MyComputedField.ts
examples/computed-field/src/tests/MyComputedField.test.ts
src/mediarithmics/plugins/computed-field/ComputedFieldBasePlugin.ts

Deserialisation of enums is now working well as it infers the enum index instead of the value (ie: USER_ACTIVITY = 0, USER_PROFILE = 1)
This lead to a plugin always returning a null state when called by the platform.
Union types will work great instead.

MICS-20753 Computed fields: Use string instead of enums

---

src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts
src/mediarithmics/api/reference/UserProfileInfo.ts
src/tests/AudienceFeedConnector.ts
src/tests/BatchedAudienceFeedConnector.ts

May be used for other information in the future but the main reason currently is to capture and share utiq fixed ids which are stored in profiles.

MICS-21957 Add user profiles on user segment update

---

package-lock.json
package.json

To upgrade its dependency path-to-regexp to 0.1.12 which fixes CVE-2024-52798

MICS-21957 Bump express version

---

examples/audience-feed/src/ExampleAudienceFeed.ts
examples/audience-feed/src/tests/index.ts
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts

Introduce 2 new feed plugin endpoints :
/authentication_status which will allow a plugin to tell if it is authenticated or not_authenticated.
/dynamic_property_values which will allow a plugin to return dynamic property values to fill select boxes

MICS-22017 Update for authed feed

---

CHANGELOG.md
examples/audience-feed/src/ExampleAudienceFeed.ts
examples/audience-feed/src/tests/index.ts
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts
src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts

rename /v1/dynamic_property_values route to /v1/dynamic_property_values_queries 
rename /v1/authentication_status route to /v1/authentication_status_queries 
for matching POST method semantic
add missing entries in changelog

MICS-22017 rename dynamic properties & authentication status routes

---

examples/audience-feed/src/tests/index.ts
src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts

remove datamart_id from /authentication route payload as we can't deduce this info from callback

MICS-22581 remove datamart_id from /authentication payload

---

CHANGELOG.md
src/mediarithmics/plugins/computed-field/ComputedFieldBasePlugin.ts

remove deprecated 'INSERT' & 'UPDATE' from Computed Field Operation use UPSERT instead

MICS-23634 remove deprecated 'INSERT' & 'UPDATE' from Computed Field Operation
