MEDIARITHMICS/plugins-nodejs-sdk

examples/activity-analyzer/src/index.ts, examples/activity-analyzer/src/tests/index.ts, examples/bid-optimizer/src/tests/index.ts, examples/email_router/src/MyPluginImpl.ts, examples/email_router/src/tests/index.ts, examples/handlebars-ad-renderer/src/MyPluginImpl.ts, examples/handlebars-ad-renderer/src/tests/index.ts, examples/simple-ad-renderer/src/tests/index.ts, src/core/class/mediarithmics/activity-analyzer/ActivityAnalyzerBasePlugin.ts, src/core/class/mediarithmics/ad-renderer/AdRendererBasePlugin.ts, src/core/class/mediarithmics/ad-renderer/AdRendererRecoTemplatePlugin.ts, src/core/class/mediarithmics/ad-renderer/AdRendererTemplatePlugin.ts, src/core/class/mediarithmics/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts, src/core/class/mediarithmics/bid-optimizer/BidOptimizerBasePlugin.ts, src/core/class/mediarithmics/common/BasePlugin.ts, src/core/class/mediarithmics/email-renderer/EmailRendererBasePlugin.ts, src/core/class/mediarithmics/email-router/EmailRouterBasePlugin.ts, src/tests/ActivityAnalyzerTests.ts, src/tests/AdRendererBaseTests.ts, src/tests/AdRendererRecoTests.ts, src/tests/AudienceFeedConnector.ts, src/tests/BasePluginTests.ts, src/tests/EmailRendererTests.ts, src/tests/EmailRouterTests.ts
The throttling will be disabled by default during testing.
=> Revert the throttling default behavior

package-lock.json, package.json, src/mediarithmics/api/core/plugin/PluginPropertyInterface.ts, src/mediarithmics/api/core/plugin/ValueInterface.ts, src/mediarithmics/index.ts, src/mediarithmics/plugins/common/BasePlugin.ts, src/mediarithmics/utils/index.ts, tsconfig.json
=> New Native Renderer

CHANGELOG.md, src/mediarithmics/index.ts, src/mediarithmics/plugins/custom-action/CustomActionBasePlugin.ts, src/mediarithmics/plugins/custom-action/CustomActionInterface.ts, src/tests/CustomActionBaseTest.ts
This commit adds the support of Custom Action plugins in the
NodeJS plugin SDK.
Tests are added for such Custom Action plugins.
An example of Custom Action is also given.
=> MICS-6966 Custom Action

src/tests/AdRendererBaseTests.ts, test_sdk_and_examples.sh
Only the first test file was run, same with `mocha --extension ts src/tests/`.
We need to investigate the issue but for now a simple shell
loop can do.
Also fix a test that never finished: the cache must be cleared so I
moved around objects to use `afterEach` like in other tests.
=> FIX: Actually run all tests

examples/custom-action/build.sh, examples/custom-action/package.json, examples/custom-action/run.sh, examples/custom-action/src/MyPluginImpl.ts, examples/custom-action/src/index.ts, examples/custom-action/src/tests/index.ts, examples/custom-action/tsconfig.json
This commit creates a dummy custom action plugin, which returns a
ok status as response.
=> MICS-6965 Dummy Custom Action

CHANGELOG.md, examples/custom-action/package.json, src/mediarithmics/plugins/custom-action/CustomActionBasePlugin.ts, src/tests/CustomActionBaseTest.ts
Call were made passing by the gateway but routes
are public.
=> MICS-7656 Fix calls on scenario_custom_actions

src/mediarithmics/plugins/activity-analyzer/ActivityAnalyzerBasePlugin.ts, src/mediarithmics/plugins/ad-renderer/base/AdRendererBasePlugin.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts, src/mediarithmics/plugins/bid-optimizer/BidOptimizerBasePlugin.ts, src/mediarithmics/plugins/common/BasePlugin.ts, src/mediarithmics/plugins/custom-action/CustomActionBasePlugin.ts, src/mediarithmics/plugins/email-renderer/base/EmailRendererBasePlugin.ts, src/mediarithmics/plugins/email-router/EmailRouterBasePlugin.ts, src/mediarithmics/plugins/recommender/RecommenderBasePlugin.ts
=> MICS-8539 Improve InstanceContext caching

CHANGELOG.md, src/mediarithmics/plugins/custom-action/CustomActionBasePlugin.ts
Fetch CustomAction and properties from PluginManager
for InstanceContext.
=> MICS-8874 CustomActionBasePlugin CustomAction and properties

src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
- Improve typing
- Add new parameter visibility on ExternalSegmentCreationPluginResponse 'public' or 'private'. If 'public' the message will be displayed in navigator as it is, otherwise it'll be obfuscated.
=> MICS-13855 Improve SDK for feeds

src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
AudienceFeed visibility change to UPPER_CASE
=> MICS-13855 AudienceFeed visibility change to UPPER_CASE

CHANGELOG.md, package-lock.json, package.json, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts, src/tests/AudienceFeedConnector.ts
update response based on new specs
=> MICS-15186 Update /segment_update response

src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts, src/tests/AudienceFeedConnector.ts
Add grouping_key to AudienceFeedBatchContext interface
=> MICS-15920 Add grouping key to audienceFeedBatchContext

CHANGELOG.md, package-lock.json, package.json, src/mediarithmics/api/core/batchupdate/BatchUpdateHandler.ts, src/mediarithmics/api/core/batchupdate/BatchUpdateInterface.ts, src/mediarithmics/api/core/plugin/PluginPropertyInterface.ts, src/mediarithmics/api/core/plugin/ValueInterface.ts, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts, src/tests/AudienceFeedConnector.ts, src/tests/BatchedAudienceFeedConnector.ts
Automatically fetch selected_identifying_resources plugin property in a dedicated field (of InstanceContexte)
To standardize the way the property is fetched and typed
=> MICS-16582 Automatically read identifying resources property

src/mediarithmics/plugins/common/BasePlugin.ts
Removed all http-proxy related code from the plugin sdk
=> MICS-16674 remove-all-http-proxy-related-code-from-the-plugin-sdk

CHANGELOG.md, README.md, src/helpers/StatsClient.spec.ts, src/helpers/StatsClient.ts, src/mediarithmics/api/core/batchupdate/BatchUpdateHandler.ts, src/mediarithmics/api/core/batchupdate/BatchUpdateInterface.ts, src/mediarithmics/api/datamart/UserActivityInterface.ts, src/tests/BatchedAudienceFeedConnector.ts
Add two new fields to BatchUpdatePluginResponse
=> MICS-16727 update-batch-update

CHANGELOG.md, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
2 new methods to create/update properties
=> MICS-17421 AudienceFeedConnectorBasePlugin update/create properties

CHANGELOG.md, src/mediarithmics/index.ts
Export missing BatchUpdateInterface
=> MICS-FIX Export BatchUpdateInterface

CHANGELOG.md, src/mediarithmics/api/core/plugin/ValueInterface.ts, src/mediarithmics/api/reference/UserIdentifierInterface.ts
Update UserDeviceTechnicalIdentifierType with TV_ADVERTISING_ID Add TV_ADVERTISING_ID to DeviceIdRegistryType
=> MICS-17555 Add missing registry type

CHANGELOG.md, src/mediarithmics/plugins/common/BasePlugin.ts, src/tests/BasePluginTests.ts
Add new route `/metadata` to BasePlugin which will give informations on plugin, node and dependencies used.
=> MICS-17429 New route /metadata

CHANGELOG.md, src/mediarithmics/api/core/plugin/ValueInterface.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
This commit refactors selected identifying resources types in order to make them more convenient to work on.
=> MICS-17594 Selected Identifying Resources Refactoring

CHANGELOG.md, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
Now it will beahved like an action route
=> MICS-18557 Update troubleshoot typing

CHANGELOG.md, src/mediarithmics/api/reference/UserIdentifierInterface.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts, src/tests/BasePluginTests.ts
Use meta from logger to improve log readibility.
=> MICS-18842 Improvement on logger for external feed

CHANGELOG.md, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
- Add a new error class AudienceFeedInstanceContextError
- Handle error visibility on instance context when creating audience
=> MICS-18865 Audience feed handle error instance context

CHANGELOG.md, examples/audience-feed/README.md, examples/audience-feed/package.json, examples/audience-feed/src/ExampleAudienceFeed.ts, examples/audience-feed/src/index.ts, examples/audience-feed/src/tests/index.ts, examples/audience-feed/tsconfig.json
Create audience feed in  /examples/audience-feed
=> MICS-18864 Add example for audience feed

CHANGELOG.md, src/mediarithmics/api/reference/DeviceIdRegistryInterface.ts
Add DeviceIdRegistryResource class and DeviceIdRegistryType enum
=> MICS-19751 Add DeviceIdRegistryResource class

CHANGELOG.md, README.md, src/mediarithmics/api/reference/DeviceIdRegistryInterface.ts
Add missing DeviceIdRegistryDatamartSelectionResource class
Add migration exemple
=> MICS-19751 add missing DeviceIdRegistryDatamartSelectionResource class

CHANGELOG.md, src/mediarithmics/api/reference/DeviceIdRegistryInterface.ts, src/mediarithmics/index.ts
add missing export for DeviceRegistry
=> MICS-19751 add missing export for DeviceRegistry

README.md, examples/computed-field/build.sh, examples/computed-field/package.json, examples/computed-field/run.sh, examples/computed-field/src/MyComputedField.ts, examples/computed-field/src/index.ts, examples/computed-field/src/tests/MyComputedField.test.ts, examples/computed-field/tsconfig.json, package-lock.json, package.json, src/mediarithmics/index.ts, src/mediarithmics/plugins/common/BasePlugin.ts, src/mediarithmics/plugins/computed-field/ComputedFieldBasePlugin.ts
Reverts MEDIARITHMICS/plugins-nodejs-sdk#202
=> MICS-18376 sdk-computedField

CHANGELOG.md, examples/audience-feed/src/ExampleAudienceFeed.ts, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
Add new generic Error who will display generic message to the end user but when logged have more informations.
- MissingPropertyError
- InvalidPropertyValueError
- FileDownloadError
- MissingRealmError
=> MICS-19906 Add new generic Error class

src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
Change from poperty_value to property_value
=> MICS-19906 Fix typo InvalidPropertyValueError -> property_value

CHANGELOG.md, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts
add MandatoryPropertyValueError class to have generic end user message
MICS-19908
=> MICS-19908 feat(audience-feed): :sparkles: add new error class

src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts
use route from plugin manager instead of core api
MICS-19908
=> MICS-19908 feat(audience-feed): :sparkles: update realms fetching

examples/computed-field/src/tests/MyComputedField.test.ts, src/mediarithmics/plugins/computed-field/ComputedFieldBasePlugin.ts
We use camel_case for all REST HTTP API.
=> MICS-CASE Fix dataType case

package-lock.json
Some vulnerabilities has been fixed, pull the updates.
=> MICS-DEPS Run npm audit --fix

src/mediarithmics/index.ts
Missing export from previous commit for profiles
=> MICS-21957 Add missing export of profiles interface

CHANGELOG.md, examples/audience-feed/src/ExampleAudienceFeed.ts, examples/audience-feed/src/tests/index.ts, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorPluginResponseInterface.ts, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts, src/mediarithmics/plugins/audience-feed-connector/AudienceFeedConnectorBasePlugin.ts, src/mediarithmics/plugins/common/BasePlugin.ts, src/tests/BasePluginTests.ts
add /authentication route to external feed plugins it will be used for receiving authentication callbacks from providers
=> MICS-22581 add /authentication route to external feed plugins

CHANGELOG.md, examples/audience-feed/src/ExampleAudienceFeed.ts, examples/audience-feed/src/tests/index.ts, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts
change params field type from /authentication route as Map are not correctly handled
=> MICS-22581 change params field type

CHANGELOG.md, examples/audience-feed/src/tests/index.ts, src/mediarithmics/api/core/audiencesegment/AudienceSegmentInterface.ts, src/mediarithmics/api/plugin/audiencefeedconnector/AudienceFeedConnectorRequestInterface.ts
add plugin_version_id in both authentication related routes 
add optionnal created_by field to AudienceSegmentExternalFeedResource
=> MICS-22625 add missing fields for impl Linkedin plugin
